#!/usr/bin/env python3
"""
convert_annotations.py

Converts the urban-tree-detection dataset (point annotations in CSV files)
into YOLO format bounding boxes for both RGB and RGB+NIR experiments.

Point annotations are expanded into square boxes of side 2*RADIUS pixels,
clipped to the 256x256 image boundary. This mirrors the approach used in
the original dataset paper (Ventura et al., 2024).

Usage:
    python convert_annotations.py \
        --dataset_dir /path/to/urban-tree-detection-data-main \
        --output_dir  /path/to/yolo_dataset \
        --radius      15

Output layout:
    yolo_dataset/
        images/rgb/train/   *.png   (3-channel)
        images/rgb/val/
        images/rgb/test/
        images/rgbn/train/  *.npy   (4-channel, float32 normalised to [0,1])
        images/rgbn/val/
        images/rgbn/test/
        labels/train/       *.txt   (shared — boxes are the same for both)
        labels/val/
        labels/test/
        dataset_rgb.yaml
        dataset_rgbn.yaml
"""

import os
import argparse
import shutil

import numpy as np
import pandas as pd
import rasterio
import cv2
from tqdm import tqdm


IMAGE_SIZE = 256   # all tiles are 256x256
N_CLASSES = 1
CLASS_ID = 0       # "tree"


def point_to_yolo_box(x, y, radius, img_size=IMAGE_SIZE):
    """Return YOLO normalised (cx, cy, w, h) from a point and radius."""
    xmin = max(x - radius, 0)
    ymin = max(y - radius, 0)
    xmax = min(x + radius, img_size - 1)
    ymax = min(y + radius, img_size - 1)
    cx = ((xmin + xmax) / 2) / img_size
    cy = ((ymin + ymax) / 2) / img_size
    w  = (xmax - xmin) / img_size
    h  = (ymax - ymin) / img_size
    return cx, cy, w, h


def read_tif(tif_path):
    """
    Read a NAIP TIFF file.
    Returns:
        rgb  : uint8 ndarray (H, W, 3)
        rgbn : float32 ndarray (H, W, 4), values in [0, 1]
    """
    with rasterio.open(tif_path) as src:
        # NAIP bands: 0=R, 1=G, 2=B, 3=NIR
        data = src.read()           # shape (4, H, W), uint8 [0-255]

    data = data.astype(np.float32)

    rgb  = np.stack([data[0], data[1], data[2]], axis=-1).astype(np.uint8)
    rgbn = np.stack([data[0], data[1], data[2], data[3]], axis=-1) / 255.0

    return rgb, rgbn


def process_split(split_name, names, dataset_dir, output_dir, radius):
    rgb_img_dir  = os.path.join(output_dir, "images", "rgb",  split_name)
    rgbn_img_dir = os.path.join(output_dir, "images", "rgbn", split_name)
    label_dir    = os.path.join(output_dir, "labels", split_name)

    for d in [rgb_img_dir, rgbn_img_dir, label_dir]:
        os.makedirs(d, exist_ok=True)

    n_trees_total = 0

    for name in tqdm(names, desc=f"[{split_name}]"):
        tif_path = os.path.join(dataset_dir, "images", f"{name}.tif")
        csv_path = os.path.join(dataset_dir, "csv",    f"{name}.csv")

        if not os.path.exists(tif_path):
            print(f"  WARNING: missing {tif_path}, skipping")
            continue

        rgb, rgbn = read_tif(tif_path)

        # Save RGB as PNG (standard 3-channel, readable by YOLOv8 directly)
        cv2.imwrite(
            os.path.join(rgb_img_dir, f"{name}.png"),
            cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
        )

        # Save RGBN as .npy (4-channel float32; loaded by custom dataset wrapper)
        np.save(os.path.join(rgbn_img_dir, f"{name}.npy"), rgbn)

        # Build YOLO label file (same boxes for both RGB and RGBN)
        label_path = os.path.join(label_dir, f"{name}.txt")
        if not os.path.exists(csv_path):
            # No trees — write empty label file
            open(label_path, "w").close()
            continue

        df = pd.read_csv(csv_path)
        lines = []
        for _, row in df.iterrows():
            cx, cy, w, h = point_to_yolo_box(int(row.x), int(row.y), radius)
            lines.append(f"{CLASS_ID} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
            n_trees_total += 1

        with open(label_path, "w") as f:
            f.write("\n".join(lines))

    return n_trees_total


def write_yaml(output_dir, mode):
    """Write a YOLO dataset YAML for 'rgb' or 'rgbn'."""
    img_subdir = os.path.join(output_dir, "images", mode)
    yaml_path  = os.path.join(output_dir, f"dataset_{mode}.yaml")

    content = f"""\
# YOLOv8 dataset config — {mode.upper()} variant
# Generated by convert_annotations.py

path: {output_dir}

train: images/{mode}/train
val:   images/{mode}/val
test:  images/{mode}/test

nc: {N_CLASSES}
names: ['tree']
"""
    with open(yaml_path, "w") as f:
        f.write(content)

    print(f"Wrote {yaml_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert urban-tree-detection point annotations to YOLO format"
    )
    parser.add_argument(
        "--dataset_dir",
        required=True,
        help="Path to urban-tree-detection-data-main/"
    )
    parser.add_argument(
        "--output_dir",
        required=True,
        help="Where to write the converted YOLO dataset"
    )
    parser.add_argument(
        "--radius",
        type=int,
        default=15,
        help="Half-side of the bounding box in pixels (default: 15 → 30x30 px box)"
    )
    args = parser.parse_args()

    for split in ["train", "val", "test"]:
        txt_path = os.path.join(args.dataset_dir, f"{split}.txt")
        names = [line.strip() for line in open(txt_path) if line.strip()]
        n = process_split(split, names, args.dataset_dir, args.output_dir, args.radius)
        print(f"  {split}: {len(names)} images, {n} trees written")

    write_yaml(args.output_dir, "rgb")
    write_yaml(args.output_dir, "rgbn")
    print("\nDone. Dataset ready for training.")


if __name__ == "__main__":
    main()
